<?php

/**
 * @file
 * Module definition
 */

define('AUTH0_DEFAULT_SCOPES', 'openid email profile');
define('AUTH0_DEFAULT_SIGNING_ALGORITHM', 'RS256');
define('AUTH0_DEFAULT_USERNAME_CLAIM', 'nickname');
define('AUTH0_MODULE_VERSION', '8.x-2.4');

/**
 * Replace a form with the lock widget.
 */
function auth0_theme() {
  return [
    'auth0_login' => [
      'template' => 'auth0-login',
      'variables' => [
        'loginCSS' => NULL,
      ],
    ],
  ];
}

/**
 * Handle users deletion, it should delete the Auth0 profile.
 */
function auth0_user_delete($account) {
  Drupal::database()->delete('auth0_user')
    ->condition('drupal_id', $account->uid->value)
    ->execute();
}

/**
 * Use Refresh Token.
 */
function auth0_signin_with_refresh_token($token) {
  $helper = \Drupal::service('auth0.helper');

  return $helper->getUserUsingRefreshToken($token);
}

/**
 * Implements hook_library_info_build().
 */
function auth0_library_info_build() {
  $config = \Drupal::service('config.factory')->get('auth0.settings');
  return [
    'auth0.widget' => [
      'js' => [
        $config->get('auth0_widget_cdn') => [
          'type' => 'external',
        ],
      ],
    ],
  ];
}
