<?php

/**
 * @file
 * Render content with tabs and other display styles.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function quicktabs_accordion_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.quicktabs_accordion':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Makes accordion rendering from jQuery UI available to the Quicktabs module.') . '</p>';
      return $output;
  }
}
