<?php

/**
 * @file
 * Installation functions for Login And Logout Redirect Per Role test module.
 */

/**
 * Implements hook_install().
 */
function login_redirect_per_role_test_install() {
  // Set a high weight so this module is called after login_redirect_per_role.
  // This makes it possible to check if hook_user_login and hook_user_logout
  // that are executed after the hooks defined in login_redirect_per_role
  // still work.
  module_set_weight('login_redirect_per_role_test', 99999);
}
