name: Gitlab Mirroring

on: [ push, create, delete ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mirror
        run: ls -lah
        shell: bash
        env:
          GITLAB_REPOSITORY: "https://gitlab.dropsolid.com/project/mauticorg.git"
          GITLAB_USERNAME: ${{ github.actor }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_MIRRORING_TOKEN }}
