name: Gitlab Mirroring

on: [ push, create, delete ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror
        run: .github/scripts/mirror.sh
        shell: bash
        env:
          GITLAB_REPOSITORY: "https://gitlab.dropsolid.com/project/mauticorg.git"
          GITLAB_USERNAME: ${{ github.actor }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_MIRRORING_TOKEN }}
          GH_EV_RF: ${{ github.event.ref }}
          GH_EV_RF_T: ${{ github.event.ref_type }}
