name: Gitlab Mirroring

on: [ push, create, delete ]

jobs:
  sync:
    name: Gitlab Mirroring
    runs-on: ubuntu-latest
    concurrency:
      group: globally-unique-mirroring
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: action-pack/gitlab-sync@v3
        with:
          username: ${{ github.actor }}
          url: https://gitlab.dropsolid.com/project/mauticorg.git
          token: ${{ secrets.GITLAB_MIRRORING_TOKEN }}
