name: Gitlab Mirroring

on: [ push, create, delete ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror
        uses: xometry/gitlab-mirror-action
        env:
          GITLAB_REPOSITORY: "https://gitlab.dropsolid.com/project/mauticorg.git"
          GITLAB_USERNAME: ${{ github.actor }}
          GITLAB_PASSWORD: ${{ secrets.GITLAB_MIRRORING_TOKEN }}
